'use strict';

var backgroundUtility = (function() {

    return {
        limitstr: function (s, limit) {
            if (!s || !limit) {
                return s;
            }
            if (s.length > limit) {
                return s.substring(0, limit);
            }
            return s;
        },

        xmlencode: function (string) {
            if (!string) { return ''; }
            return string.replace(/\&/g, '&' + 'amp;').replace(/</g, '&' + 'lt;')
                .replace(/>/g, '&' + 'gt;').replace(/\'/g, '&' + 'apos;').replace(/\"/g, '&' + 'quot;');
        },

        xmldecode: function (string) {
            return string.replace(/\&amp;/g, '&').replace(/\&lt;/g, '<')
                .replace(/\&gt;/g, '>').replace(/\&apos;/g, '\'').replace(/\&quot;/g, '"');
        }
    };

})();
'use strict';

var geographyData = (function() {

    var makeCaseInsensitiveDict = function(source) {
        var result = {};
        var placeCode;

        for(var placeName in source) {
            if (source.hasOwnProperty(placeName)) {
                placeCode = source[placeName];
                result[placeName.toLowerCase()] = placeCode;
            }
        }

        return result;
    };

    var stateCodeLookup = {
        'Acre': 'AC',
        'Agrigento': 'AG',
        'Aguascalientes': 'AG',
        'Alabama': 'AL',
        'Alagoas': 'AL',
        'Alaska': 'AK',
        'Alberta': 'AB',
        'Alessandria': 'AL',
        'Amapá': 'AP',
        'Amazonas': 'AM',
        'Ancona': 'AN',
        'Andaman and Nicobar Islands': 'AN',
        'Andhra Pradesh': 'AP',
        'Anhui': '34',
        'Aosta': 'AO',
        'Arezzo': 'AR',
        'Arizona': 'AZ',
        'Arkansas': 'AR',
        'Arunachal Pradesh': 'AR',
        'Ascoli Piceno': 'AP',
        'Assam': 'AS',
        'Asti': 'AT',
        'Australian Capital Territory': 'ACT',
        'Avellino': 'AV',
        'Bahia': 'BA',
        'Baja California': 'BC',
        'Baja California Sur': 'BS',
        'Bari': 'BA',
        'Barletta-Andria-Trani': 'BT',
        'Beijing': '11',
        'Belluno': 'BL',
        'Benevento': 'BN',
        'Bergamo': 'BG',
        'Biella': 'BI',
        'Bihar': 'BR',
        'Bologna': 'BO',
        'Bolzano': 'BZ',
        'Brescia': 'BS',
        'Brindisi': 'BR',
        'British Columbia': 'BC',
        'Cagliari': 'CA',
        'California': 'CA',
        'Caltanissetta': 'CL',
        'Campeche': 'CM',
        'Campobasso': 'CB',
        'Carbonia-Iglesias': 'CI',
        'Carlow': 'CW',
        'Caserta': 'CE',
        'Catania': 'CT',
        'Catanzaro': 'CZ',
        'Cavan': 'CN',
        'Ceará': 'CE',
        'Chandigarh': 'CH',
        'Chhattisgarh': 'CT',
        'Chiapas': 'CS',
        'Chieti': 'CH',
        'Chihuahua': 'CH',
        'Chinese Taipei': '71',
        'Chongqing': '50',
        'Clare': 'CE',
        'Coahuila': 'CO',
        'Colima': 'CL',
        'Colorado': 'CO',
        'Como': 'CO',
        'Connecticut': 'CT',
        'Cork': 'CO',
        'Cosenza': 'CS',
        'Cremona': 'CR',
        'Crotone': 'KR',
        'Cuneo': 'CN',
        'Dadra and Nagar Haveli': 'DN',
        'Daman and Diu': 'DD',
        'Delaware': 'DE',
        'Delhi': 'DL',
        'District of Columbia': 'DC',
        'Distrito Federal': 'DF',
        'Donegal': 'DL',
        'Dublin': 'D',
        'Durango': 'DG',
        'Enna': 'EN',
        'Espírito Santo': 'ES',
        'Federal District': 'DF',
        'Fermo': 'FM',
        'Ferrara': 'FE',
        'Florence': 'FI',
        'Florida': 'FL',
        'Foggia': 'FG',
        'Forlì-Cesena': 'FC',
        'Frosinone': 'FR',
        'Fujian': '35',
        'Galway': 'G',
        'Gansu': '62',
        'Genoa': 'GE',
        'Georgia': 'GA',
        'Goa': 'GA',
        'Goiás': 'GO',
        'Gorizia': 'GO',
        'Grosseto': 'GR',
        'Guanajuato': 'GT',
        'Guangdong': '44',
        'Guangxi': '45',
        'Guerrero': 'GR',
        'Guizhou': '52',
        'Gujarat': 'GJ',
        'Hainan': '46',
        'Haryana': 'HR',
        'Hawaii': 'HI',
        'Hebei': '13',
        'Heilongjiang': '23',
        'Henan': '41',
        'Hidalgo': 'HG',
        'Himachal Pradesh': 'HP',
        'Hong Kong': '91',
        'Hubei': '42',
        'Hunan': '43',
        'Idaho': 'ID',
        'Illinois': 'IL',
        'Imperia': 'IM',
        'Indiana': 'IN',
        'Iowa': 'IA',
        'Isernia': 'IS',
        'Jalisco': 'JA',
        'Jammu and Kashmir': 'JK',
        'Jharkhand': 'JH',
        'Jiangsu': '32',
        'Jiangxi': '36',
        'Jilin': '22',
        'Kansas': 'KS',
        'Karnataka': 'KA',
        'Kentucky': 'KY',
        'Kerala': 'KL',
        'Kerry': 'KY',
        'Kildare': 'KE',
        'Kilkenny': 'KK',
        'L&#39, Aquila': 'AQ',
        'Lakshadweep': 'LD',
        'Laois': 'LS',
        'La Spezia': 'SP',
        'Latina': 'LT',
        'Lecce': 'LE',
        'Lecco': 'LC',
        'Leitrim': 'LM',
        'Liaoning': '21',
        'Limerick': 'LK',
        'Livorno': 'LI',
        'Lodi': 'LO',
        'Longford': 'LD',
        'Louisiana': 'LA',
        'Louth': 'LH',
        'Lucca': 'LU',
        'Macao': '92',
        'Macerata': 'MC',
        'Madhya Pradesh': 'MP',
        'Maharashtra': 'MH',
        'Maine': 'ME',
        'Manipur': 'MN',
        'Manitoba': 'MB',
        'Mantua': 'MN',
        'Maranhão': 'MA',
        'Maryland': 'MD',
        'Massa and Carrara': 'MS',
        'Massachusetts': 'MA',
        'Matera': 'MT',
        'Mato Grosso': 'MT',
        'Mato Grosso do Sul': 'MS',
        'Mayo': 'MO',
        'Meath': 'MH',
        'Medio Campidano': 'VS',
        'Meghalaya': 'ML',
        'Messina': 'ME',
        'Mexico State': 'ME',
        'Michigan': 'MI',
        'Michoacán': 'MI',
        'Milan': 'MI',
        'Minas Gerais': 'MG',
        'Minnesota': 'MN',
        'Mississippi': 'MS',
        'Missouri': 'MO',
        'Mizoram': 'MZ',
        'Modena': 'MO',
        'Monaghan': 'MN',
        'Montana': 'MT',
        'Monza and Brianza': 'MB',
        'Morelos': 'MO',
        'Nagaland': 'NL',
        'Naples': 'NA',
        'Nayarit': 'NA',
        'Nebraska': 'NE',
        'Nei Mongol': '15',
        'Nevada': 'NV',
        'New Brunswick': 'NB',
        'Newfoundland and Labrador': 'NL',
        'New Hampshire': 'NH',
        'New Jersey': 'NJ',
        'New Mexico': 'NM',
        'New South Wales': 'NSW',
        'New York': 'NY',
        'Ningxia': '64',
        'North Carolina': 'NC',
        'North Dakota': 'ND',
        'Northern Territory': 'NT',
        'Northwest Territories': 'NT',
        'Novara': 'NO',
        'Nova Scotia': 'NS',
        'Nuevo León': 'NL',
        'Nunavut': 'NU',
        'Nuoro': 'NU',
        'Oaxaca': 'OA',
        'Odisha': 'OR',
        'Offaly': 'OY',
        'Ogliastra': 'OG',
        'Ohio': 'OH',
        'Oklahoma': 'OK',
        'Olbia-Tempio': 'OT',
        'Ontario': 'ON',
        'Oregon': 'OR',
        'Oristano': 'OR',
        'Padua': 'PD',
        'Palermo': 'PA',
        'Pará': 'PA',
        'Paraíba': 'PB',
        'Paraná': 'PR',
        'Parma': 'PR',
        'Pavia': 'PV',
        'Pennsylvania': 'PA',
        'Pernambuco': 'PE',
        'Perugia': 'PG',
        'Pesaro and Urbino': 'PU',
        'Pescara': 'PE',
        'Piacenza': 'PC',
        'Piauí': 'PI',
        'Pisa': 'PI',
        'Pistoia': 'PT',
        'Pordenone': 'PN',
        'Potenza': 'PZ',
        'Prato': 'PO',
        'Prince Edward Island': 'PE',
        'Puducherry': 'PY',
        'Puebla': 'PB',
        'Punjab': 'PB',
        'Qinghai': '63',
        'Quebec': 'QC',
        'Queensland': 'QLD',
        'Querétaro': 'QE',
        'Quintana Roo': 'QR',
        'Ragusa': 'RG',
        'Rajasthan': 'RJ',
        'Ravenna': 'RA',
        'Reggio Calabria': 'RC',
        'Reggio Emilia': 'RE',
        'Rhode Island': 'RI',
        'Rieti': 'RI',
        'Rimini': 'RN',
        'Rio de Janeiro': 'RJ',
        'Rio Grande do Norte': 'RN',
        'Rio Grande do Sul': 'RS',
        'Rome': 'RM',
        'Rondônia': 'RO',
        'Roraima': 'RR',
        'Roscommon': 'RN',
        'Rovigo': 'RO',
        'Salerno': 'SA',
        'San Luis Potosí': 'SL',
        'Santa Catarina': 'SC',
        'São Paulo': 'SP',
        'Saskatchewan': 'SK',
        'Sassari': 'SS',
        'Savona': 'SV',
        'Sergipe': 'SE',
        'Shaanxi': '61',
        'Shandong': '37',
        'Shanghai': '31',
        'Shanxi': '14',
        'Sichuan': '51',
        'Siena': 'SI',
        'Sikkim': 'SK',
        'Sinaloa': 'SI',
        'Sligo': 'SO',
        'Sondrio': 'SO',
        'Sonora': 'SO',
        'South Australia': 'SA',
        'South Carolina': 'SC',
        'South Dakota': 'SD',
        'Syracuse': 'SR',
        'Tabasco': 'TB',
        'Tamaulipas': 'TM',
        'Tamil Nadu': 'TN',
        'Taranto': 'TA',
        'Tasmania': 'TAS',
        'Tennessee': 'TN',
        'Teramo': 'TE',
        'Terni': 'TR',
        'Texas': 'TX',
        'Tianjin': '12',
        'Tipperary': 'TA',
        'Tlaxcala': 'TL',
        'Tocantins': 'TO',
        'Trapani': 'TP',
        'Trento': 'TN',
        'Treviso': 'TV',
        'Trieste': 'TS',
        'Tripura': 'TR',
        'Turin': 'TO',
        'Udine': 'UD',
        'Utah': 'UT',
        'Uttarakhand': 'UT',
        'Uttar Pradesh': 'UP',
        'Varese': 'VA',
        'Venice': 'VE',
        'Veracruz': 'VE',
        'Verbano-Cusio-Ossola': 'VB',
        'Vercelli': 'VC',
        'Vermont': 'VT',
        'Verona': 'VR',
        'Vibo Valentia': 'VV',
        'Vicenza': 'VI',
        'Victoria': 'VIC',
        'Virginia': 'VA',
        'Viterbo': 'VT',
        'Washington': 'WA',
        'Waterford': 'WD',
        'West Bengal': 'WB',
        'Western Australia': 'WA',
        'Westmeath': 'WH',
        'West Virginia': 'WV',
        'Wexford': 'WX',
        'Wicklow': 'WW',
        'Wisconsin': 'WI',
        'Wyoming': 'WY',
        'Xinjiang': '65',
        'Xizang': '54',
        'Yucatán': 'YU',
        'Yukon Territories': 'YT',
        'Yunnan': '53',
        'Zacatecas': 'ZA',
        'Zhejiang': '33'
    };

    var countryCodeLookup = {
        'Afghanistan': 'AF',
        'Aland Islands': 'AX',
        'Albania': 'AL',
        'Algeria': 'DZ',
        'Andorra': 'AD',
        'Angola': 'AO',
        'Anguilla': 'AI',
        'Antarctica': 'AQ',
        'Antigua and Barbuda': 'AG',
        'Argentina': 'AR',
        'Armenia': 'AM',
        'Aruba': 'AW',
        'Australia': 'AU',
        'Austria': 'AT',
        'Azerbaijan': 'AZ',
        'Bahamas': 'BS',
        'Bahrain': 'BH',
        'Bangladesh': 'BD',
        'Barbados': 'BB',
        'Belarus': 'BY',
        'Belgium': 'BE',
        'Belize': 'BZ',
        'Benin': 'BJ',
        'Bermuda': 'BM',
        'Bhutan': 'BT',
        'Bolivia, Plurinational State of': 'BO',
        'Bonaire, Sint Eustatius and Saba': 'BQ',
        'Bosnia and Herzegovina': 'BA',
        'Botswana': 'BW',
        'Bouvet Island': 'BV',
        'Brazil': 'BR',
        'British Indian Ocean Territory': 'IO',
        'Brunei Darussalam': 'BN',
        'Bulgaria': 'BG',
        'Burkina Faso': 'BF',
        'Burundi': 'BI',
        'Cambodia': 'KH',
        'Cameroon': 'CM',
        'Canada': 'CA',
        'Cape Verde': 'CV',
        'Cayman Islands': 'KY',
        'Central African Republic': 'CF',
        'Chad': 'TD',
        'Chile': 'CL',
        'China': 'CN',
        'Chinese Taipei': 'TW',
        'Christmas Island': 'CX',
        'Cocos (Keeling) Islands': 'CC',
        'Colombia': 'CO',
        'Comoros': 'KM',
        'Congo': 'CG',
        'Congo, the Democratic Republic of the': 'CD',
        'Cook Islands': 'CK',
        'Costa Rica': 'CR',
        'Cote d&#39, Ivoire': 'CI',
        'Croatia': 'HR',
        'Cuba': 'CU',
        'Curaçao': 'CW',
        'Cyprus': 'CY',
        'Czech Republic': 'CZ',
        'Denmark': 'DK',
        'Djibouti': 'DJ',
        'Dominica': 'DM',
        'Dominican Republic': 'DO',
        'Ecuador': 'EC',
        'Egypt': 'EG',
        'El Salvador': 'SV',
        'Equatorial Guinea': 'GQ',
        'Eritrea': 'ER',
        'Estonia': 'EE',
        'Ethiopia': 'ET',
        'Falkland Islands (Malvinas)': 'FK',
        'Faroe Islands': 'FO',
        'Fiji': 'FJ',
        'Finland': 'FI',
        'France': 'FR',
        'French Guiana': 'GF',
        'French Polynesia': 'PF',
        'French Southern Territories': 'TF',
        'Gabon': 'GA',
        'Gambia': 'GM',
        'Georgia': 'GE',
        'Germany': 'DE',
        'Ghana': 'GH',
        'Gibraltar': 'GI',
        'Greece': 'GR',
        'Greenland': 'GL',
        'Grenada': 'GD',
        'Guadeloupe': 'GP',
        'Guatemala': 'GT',
        'Guernsey': 'GG',
        'Guinea': 'GN',
        'Guinea-Bissau': 'GW',
        'Guyana': 'GY',
        'Haiti': 'HT',
        'Heard Island and McDonald Islands': 'HM',
        'Holy See (Vatican City State)': 'VA',
        'Honduras': 'HN',
        'Hungary': 'HU',
        'Iceland': 'IS',
        'India': 'IN',
        'Indonesia': 'ID',
        'Iran, Islamic Republic of': 'IR',
        'Iraq': 'IQ',
        'Ireland': 'IE',
        'Isle of Man': 'IM',
        'Israel': 'IL',
        'Italy': 'IT',
        'Jamaica': 'JM',
        'Japan': 'JP',
        'Jersey': 'JE',
        'Jordan': 'JO',
        'Kazakhstan': 'KZ',
        'Kenya': 'KE',
        'Kiribati': 'KI',
        'Korea, Democratic People&#39, s Republic of': 'KP',
        'Korea, Republic of': 'KR',
        'Kuwait': 'KW',
        'Kyrgyzstan': 'KG',
        'Lao People&#39, s Democratic Republic': 'LA',
        'Latvia': 'LV',
        'Lebanon': 'LB',
        'Lesotho': 'LS',
        'Liberia': 'LR',
        'Libyan Arab Jamahiriya': 'LY',
        'Liechtenstein': 'LI',
        'Lithuania': 'LT',
        'Luxembourg': 'LU',
        'Macao': 'MO',
        'Macedonia, the former Yugoslav Republic of': 'MK',
        'Madagascar': 'MG',
        'Malawi': 'MW',
        'Malaysia': 'MY',
        'Maldives': 'MV',
        'Mali': 'ML',
        'Malta': 'MT',
        'Martinique': 'MQ',
        'Mauritania': 'MR',
        'Mauritius': 'MU',
        'Mayotte': 'YT',
        'Mexico': 'MX',
        'Moldova, Republic of': 'MD',
        'Monaco': 'MC',
        'Mongolia': 'MN',
        'Montenegro': 'ME',
        'Montserrat': 'MS',
        'Morocco': 'MA',
        'Mozambique': 'MZ',
        'Myanmar': 'MM',
        'Namibia': 'NA',
        'Nauru': 'NR',
        'Nepal': 'NP',
        'Netherlands': 'NL',
        'New Caledonia': 'NC',
        'New Zealand': 'NZ',
        'Nicaragua': 'NI',
        'Niger': 'NE',
        'Nigeria': 'NG',
        'Niue': 'NU',
        'Norfolk Island': 'NF',
        'Norway': 'NO',
        'Oman': 'OM',
        'Pakistan': 'PK',
        'Palestinian Territory, Occupied': 'PS',
        'Panama': 'PA',
        'Papua New Guinea': 'PG',
        'Paraguay': 'PY',
        'Peru': 'PE',
        'Philippines': 'PH',
        'Pitcairn': 'PN',
        'Poland': 'PL',
        'Portugal': 'PT',
        'Qatar': 'QA',
        'Reunion': 'RE',
        'Romania': 'RO',
        'Russian Federation': 'RU',
        'Rwanda': 'RW',
        'Saint Barthélemy': 'BL',
        'Saint Helena, Ascension and Tristan da Cunha': 'SH',
        'Saint Kitts and Nevis': 'KN',
        'Saint Lucia': 'LC',
        'Saint Martin (French part)': 'MF',
        'Saint Pierre and Miquelon': 'PM',
        'Saint Vincent and the Grenadines': 'VC',
        'Samoa': 'WS',
        'San Marino': 'SM',
        'Sao Tome and Principe': 'ST',
        'Saudi Arabia': 'SA',
        'Senegal': 'SN',
        'Serbia': 'RS',
        'Seychelles': 'SC',
        'Sierra Leone': 'SL',
        'Singapore': 'SG',
        'Sint Maarten (Dutch part)': 'SX',
        'Slovakia': 'SK',
        'Slovenia': 'SI',
        'Solomon Islands': 'SB',
        'Somalia': 'SO',
        'South Africa': 'ZA',
        'South Georgia and the South Sandwich Islands': 'GS',
        'South Sudan': 'SS',
        'Spain': 'ES',
        'Sri Lanka': 'LK',
        'Sudan': 'SD',
        'Suriname': 'SR',
        'Svalbard and Jan Mayen': 'SJ',
        'Swaziland': 'SZ',
        'Sweden': 'SE',
        'Switzerland': 'CH',
        'Syrian Arab Republic': 'SY',
        'Tajikistan': 'TJ',
        'Tanzania, United Republic of': 'TZ',
        'Thailand': 'TH',
        'Timor-Leste': 'TL',
        'Togo': 'TG',
        'Tokelau': 'TK',
        'Tonga': 'TO',
        'Trinidad and Tobago': 'TT',
        'Tunisia': 'TN',
        'Turkey': 'TR',
        'Turkmenistan': 'TM',
        'Turks and Caicos Islands': 'TC',
        'Tuvalu': 'TV',
        'Uganda': 'UG',
        'Ukraine': 'UA',
        'United Arab Emirates': 'AE',
        'United Kingdom': 'GB',
        'United States': 'US',
        'Uruguay': 'UY',
        'Uzbekistan': 'UZ',
        'Vanuatu': 'VU',
        'Venezuela, Bolivarian Republic of': 'VE',
        'Viet Nam': 'VN',
        'Virgin Islands, British': 'VG',
        'Wallis and Futuna': 'WF',
        'Western Sahara': 'EH',
        'Yemen': 'YE',
        'Zambia': 'ZM',
        'Zimbabwe': 'ZW'
    };

    var usStateCodes = [
        'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL',
        'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA',
        'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE',
        'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI',
        'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV',
        'WY'
    ];

    var usStateDict = {};
    for(var code in usStateCodes) {
        usStateDict[code] = true;
    }

    var isUSStateCode = function(stateCode) {
        return !!(usStateDict[stateCode.toUpperCase()]);
    };

    return {
        stateNameLowerToStateCodeDict:  makeCaseInsensitiveDict(stateCodeLookup),
        countryNameLowerToCountryCodeDict:  makeCaseInsensitiveDict(countryCodeLookup),
        isUSStateCode: isUSStateCode
    };

})();